---
# defaults file for oracle-db

transport: local
# local
# web

transport_web: http://my-storage.example.com

trasnport_local: /tmp

oracle_version: 12
patch_version: 12.2.0.1

oracle_images:
  - linuxx64_12201_database.zip
  #- linuxamd64_12201_database_1of2.zip
  #- linuxamd64_12201_database_2of2.zip

oracle_base: /opt/oracledb
unqname: orcl
sid: orcl

# Password for administrative accounts
# All databases include the SYS, SYSTEM, SYSMAN and DBSNMP administrative
# accounts. To protect these accounts from unauthorized access, their
# passwords must be changed according Oracle password policy.

# Password for all database users
syspass: <SYS_PASSWORD>

# SYS account password
syspassword: <SYS_PASSWORD>

# SYSTEM account password
systempassword: <SYSTEM_PASSWORD>

# SYSMAN account password
sysmanpassword: <SYSMAN_PASSWORD>

# DBSNMP account password
dbsnmppassword: <DBSNMP_PASSWORD>

# Initial user password
db_user_password: <SCHEMA_PASSWORD>

# If a multitenant DB with one or more pluggable DBs is created
pdbadminpassword: <PDBADMIN_PASSWORD>

db_user: oracle
db_tablespace: oracle
db_startup_timeout: 300

# set default `count=` value for `dd` for copies only this number of blocks
oracle_db_swap_count: "{{ 16384 if ansible_memtotal_mb > 10240 else (ansible_memtotal_mb * 1.5)| \
                      round|int if ansible_memtotal_mb > 2048 else 8192 }}"
oracle_db_swapfile: /oracle-swapfile
# For Oracle Universal Installer
inventory_directory: /opt/oraInventory
ora_inst: /etc/oraInst.loc
