---

- name: Execute start cluster script
  shell: "{{ wlst_command }} {{ working_directory }}/start_clusters.py"
  become_user: '{{ oracle_user }}'
  register: command_result


- name: Validate the create output to see all went well.
  assert:
        that:
           - command_result.stdout | search("successfully started wls domain")
        msg: "starting the domain failed, check the logs.."
  when: command_result.changed
