---

- name: create the default directories required"
  become: true
  become_user: root
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ default_directories }}"
  when: default_directories is defined


- name: create the additional directoris required
  become: true
  become_user: root
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ additional_directories }}"
  when: additional_directories is defined



- name: create the directoris required for the role.
  become: true
  become_user: root
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ role_directories }}"
  when: role_directories is defined
