---
- set_fact:
   template_name: "{{ domain_template_dir }}/{{ wls_domain_name }}_{{ soa_env }}.jar"

- name: create the directory required to store packed wld
  become_user: root
  file:
    state: directory
    path: "{{ domain_template_dir }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"
  
- name: Copy domain template file to managed servers
  become_user: root
  copy:
    src: "/tmp/{{ wls_domain_name }}/{{ wls_domain_name }}_{{ soa_env }}.jar"
    dest: "{{ template_name }}"
    owner: "{{ oracle_user }}"
    mode: '0644'

- name: unpack the domain using the unpack command .
  shell: "{{ wl_unpack_command }} -domain={{ wls_domain_home }} -app_dir={{ wls_apps_home }} -template={{ template_name }}"
  args:
      creates: "{{ wls_domain_home }}/bin"
  become: yes
  become_user: "{{ oracle_user }}"
  register: command_result

- name: Validate the unpack output to see all went well.
  assert:
    that:
      - "'succeed.*close template' not in command_result.stdout_lines"
    msg: "unpack failed, check the logs.."
  when: command_result.changed
