
- include: prepare_for_copy.yml

- name: Copy archived files and extract
  shell: "tar -xvf {{ item.source }} {{ item.to_folder }}/"
  args:
       chdir: "{{ item.destination }}"
# tar will either preserve the attributes, or use te one of the oracle_user
# but we need to assign t a specific user.
- name: Change the ownership of the files, to the owner specified
  shell: "chown -R {{ owner }}:{{ group }} {{ item.destination }}/{{ item.to_folder }}/"

- name: Change the mode of the files, to the one specified
  shell: "chmod -R {{ mode }} {{ item.destination }}/{{ item.to_folder }}/"
