
- include: prepare_for_copy.yml

- name: Copy file to the destination
  copy:
    src: "{{ item[0].source }}"
    dest: "{{ destination_folder }}/{{ item[0].to_name }}"
    remote_src: yes
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
