---

- name: Template the silent response file.
  become: true
  become_user: root
  template:
    src: templates/silent.xml.j2
    dest: "{{ working_directory }}/silent.xml"
    mode: 0755
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"
    
- name: create installs directory
  become: true
  become_user: root
  file:
    path: "{{ app_mount }}/install"
    state: directory
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"
    mode: "0755"
    
- name: Copy infra install file to the destination
  become: true
  become_user: root
  copy:
    src: "{{ installers }}/{{ infra_installer_file }}"
    dest: "{{ app_mount }}/install"
    remote_src: no
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"
    mode: "0755"

- name: Verify /tmp is accessible
  become: true
  become_user: root
  file:
    path: /tmp
    state: directory
    mode: '0777'

- name: install infra if not present already.
  command: "{{ java_home}}/bin/java -Xms1024m -Xmx1024m -jar {{ app_mount }}/install/{{ infra_installer_file }} -silent -ignoreSysPrereqs -invPtrLoc {{ invptr_location }} -responseFile {{ working_directory }}/silent.xml"
  become_user: "{{ oracle_user }}"
  args:
    creates: "{{ oracle_common_home }}"
  register: command_result

- name: Validate the create output to see all went well.
  become: true
  become_user: root
  assert:
    that:
      - "'The installation of Oracle Fusion Middleware.*completed successfully' not in command_result.stdout_lines"
    msg: "The installation of Oracle Fusion Middleware failed. Please check the logs."
  when: command_result.changed

- name: validate infra version
  become: true
  become_user: root
  command: "{{ java_home }}/bin/java -cp {{ wls_jar }} weblogic.version"
  register: wls_version_check

- assert:
    that:
       - infra_base_version in wls_version_check.stdout
    msg: "Required  Weblogic version {{ infra_base_version }} is not installed, failing.."
  become: true
  become_user: root
