---
#
- name: create group
  group:
    name: "{{ oracle_soa_group }}"
    state: present

- name: create user
  user:
    name: "{{ oracle_soa_user }}"
    group: "{{ oracle_soa_group }}"
    state: present

- name: prepare oracle inventory parameters
  template:
    src: ora_inst.loc.j2
    dest: "/etc/oraInst.loc"

- name: prepare installation directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ oracle_soa_user }}"
    group: "{{ oracle_soa_group }}"
  with_items:
    - "{{ oracle_soa_oracle_base }}"
    - "{{ oracle_soa_oracle_home }}"
    - "{{ oracle_soa_inventory_directory }}"
