---
# vars file for oracle-soa

oracle_soa_user: oraclefmw
oracle_soa_group: ofmwinstall
oracle_soa_oracle_base: "/opt/oraclefmw"
oracle_soa_oracle_home: "/opt/oraclefmw/product/oracle_home"
oracle_soa_soa_home: "{{ oracle_soa_oracle_home }}/soa"
oracle_soa_wls_home: "{{ oracle_soa_oracle_home }}/wlserver"
oracle_soa_inventory_file: "{{ oracle_soa_oracle_base }}/oraInst.loc"
oracle_soa_inventory_directory: "/opt/oraclefmw/inventory"
oracle_soa_jdev_command: jdev

oracle_soa_response_file: "{{ oracle_soa_oracle_base }}/soa-install.rsp"

oracle_soa_already_installed: false
