---
- name: template and copy wlst script file for configuring domain.
  become_user: root
  template:
    src: "{{ item.src }}"
    dest: "{{ working_directory }}/{{ item.dest }}"
    mode: 0755
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"
  with_items:
    - { "src": "fix_domain.py", "dest": "fix_domain.py" }
    # - { "src": "soaDomain.props.j2", "dest": "soaDomain.properties" }
