- name: set oracle home
  lineinfile:
   dest: "{{ oracle_user_home }}/.bash_profile"
   regexp: "{{ item.regexp }}"
   line: "{{ item.line }}"
   insertbefore: "export PATH"
  with_items:
    -
      regexp: ^ORACLE_HOME=
      line: "ORACLE_HOME={{ oracle_home }}"
      state: present
    -
      regexp: PATH=\$ORACLE_HOME/bin
      line: PATH=$ORACLE_HOME/bin:$PATH
      state: present
    -
      regexp: ^export ORACLE_HOME
      line: export ORACLE_HOME
      state: present

# how to make this idempotent? should not run if ran already.
- name: run post-installation scripts as root
  shell: "{{ item }}"
  with_items:
    - "{{ inventory_location }}/orainstRoot.sh"
    - "{{ oracle_home }}/root.sh"
