---
- name: template and copy wlst script file for building domain.
  template:
    src: create_wl_domain.py.j2
    dest: "{{ working_directory }}/create_wl_domain.py"
    mode: 0755
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"

- name: template  wlst constructors
  template:
    src: wlst_utility/constructors.py.j2
    dest: "{{ working_directory }}/wlst_utility/constructors.py"
    mode: 0755
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"

- name: template constructors dependency.
  template:
    src: wlst_utility/__init__.py.j2
    dest: "{{ working_directory }}/wlst_utility/__init__.py"
    mode: 0755
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"
