---
- hosts: bpm-admin
  vars_files:
    - ../vars/fusion.yml
    - ../vars/bpm/common.yml
    - ../vars/bpm/wls_domain.yml
    - ../vars/bpm/common_resources_to_copy.yml
  roles:
    - role: rcu
    - role: configure-domain
#    - role: copy-resources
    - role: configure-nodemanager
    - role: start-adminsvr
    - role: pack-domain