---
- hosts: bpm
  vars_files:
    - ../vars/fusion.yml
    - ../vars/bpm/common.yml
  roles:
    - role: install-java
    - role: install-middleware-infrastructure    # install-weblogic
    - role: patch-middleware                     # patch-weblogic
    - role: install-soa                          # install-soa
    - role: patch-soa                            # patch-soa

