---

- hosts: db
  vars_files:
    - ../vars/db/oracle12.yml
  vars:
    - version: 12

  roles:
#    - common
    - install-oracle-db
    #- role: ansible-role-install-db-{{ release }}
    #- role: ansible-role-shutdown-db
    #- role: ansible-role-db-rman-import
    #- role: ansible-role-reconfigure-listner
