---
- hosts: osb-managed
  vars_files:
    - ../vars/fusion.yml
    - ../vars/bpm/common.yml
    - ../vars/bpm/wls_domain.yml
  roles:
    - role: unpack-domain-for-mgd-svrs
    - role: configure-nodemanager