---
- hosts: osb-admin
  vars_files:
    - ../vars/fusion.yml
    - ../vars/bpm/common.yml
    - ../vars/bpm/wls_domain.yml
    - ../vars/bpm/common_resources_to_copy.yml
  roles:
    - role: customize-users
    # TODO: Add JMS resources configuration ROLE
    - role: customize-jms
    # TODO: Add DS resources configuration ROLE
#    - role: customize-jdbc
    # TODO: Add Adapter Redeployment ROLE
    # TODO: Add DB adapter, JMS Adapter configuration ROLE
#    - role: customize-adapters
    # TODO: Add App Deployments ROLE
    # TODO: Add JKS modification ROLE
    # TODO: Add OID, Asserter providers configuration ROLE
    # TODO: Add UMS XMAIL resources configuration ROLE
