---

- name: Template the silent response file.
  template:
    src: templates/silent.xml.j2
    dest: "{{ working_directory }}/silent.xml"
    mode: 0755
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"

- name: install infra if not present already.
  command: "{{ java_home}}/bin/java -Xms1024m -Xmx1024m -jar {{ infra_installer }} -ignorePrereq -invPtrLoc {{ invptr_location }} -silent -responseFile {{ working_directory }}/silent.xml"
  become_user: "{{ oracle_user }}"
  args:
    creates: "{{ middleware_home }}"
  register: command_result

- name: Validate the create output to see all went well.
  assert:
    that:
      - command_result.stdout | search("The installation of Oracle Fusion Middleware.*completed successfully")
    msg: "The installation of Oracle Fusion Middleware failed. Please check the logs."
  when: command_result.changed

- name: validate infra version
  command: "{{ java_home }}/bin/java -cp {{ wls_jar }} weblogic.version"
  register: wls_version_check

- assert:
    that:
       - infra_base_version in wls_version_check.stdout
    msg: "Required  Weblogic version {{ infra_base_version }} is not installed, failing.."
